<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:v="urn:schemas-microsoft-com:vml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Welcome, please activate</title>
</head>
<body>
    <p>Welcome aboard $name$,</p>
    <p>
    Your account is now setup (your username is <strong class="highlight">$login$</strong>) and you’re almost ready to go. There's one more step to complete: please verify your email address by activating your account using the link below...
    </p>

    <h2>Activate your account</h2>
    <p>
      <a href="$activation_url$">$activation_url$</a>
    </p>

</body>
</html>
