<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:v="urn:schemas-microsoft-com:vml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Reset your password</title>

</head>
<body>


  <p >
    $name$, need help with a forgotten password?
  </p>

  <div >
    <p>
      Please click the following link to reset your password:
      <br>
      <a href="$url$">$url$</a>
    </p>
    <p>
      Feel free to email support@backchat.io if this reset-password request is suspicious.
    </p>


</body>
</html>
